apiVersion: v1
kind: Pod
metadata:
  name: test-nic-resources
  namespace: dk 
  annotations:
    k8s.v1.cni.cncf.io/networks: |
      [
        {"name":"sriov-rdma-vf","namespace":"default","interface":"net1"},
        {"name":"sriov-rdma-vf","namespace":"default","interface":"net2"},
      ]
spec:
  tolerations:
    - operator: Exists
  restartPolicy: Never
  terminationGracePeriodSeconds: 1
  containers:
  - name: networking-debug-container
    image: quay.io/rajjoshi/networking-debug-container:latest
    imagePullPolicy: Always  # Always pull the latest image, even if tag is the same
    resources:
      limits:
        amd.com/gpu: 2
        nvidia.com/sriov-rdma-vf: 2
      requests:
        amd.com/gpu: 2
        nvidia.com/sriov-rdma-vf: 2
    # Access to InfiniBand devices
    volumeMounts:
    - name: dev-infiniband
      mountPath: /dev/infiniband
    
    command: ["/bin/bash", "-c"]
    args: 
    - |
      sleep infinity
  
  volumes:
  - name: dev-infiniband
    hostPath:
      path: /dev/infiniband
      type: Directory